// <auto-generated />
using System;
using Dentalla.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dentalla.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DentallaDbContext))]
    partial class DentallaDbContextModelSnapshot : ModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dentalla.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RoleContext")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ActorUserAccountId", "OccurredAtUtc");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.ToTable("AuditEvents", "audit");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndedLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("PatientId", "StartedLocal");

                    b.HasIndex("StaffProfileId", "StartedLocal");

                    b.ToTable("Encounters", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.PerformedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short?>("ComplexityId")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("ComplexityValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DiagnosisCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LegacyManipulationOk")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrimeCost")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SourceUnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tooth")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceCatalogItemId");

                    b.HasIndex("StaffProfileId");

                    b.ToTable("PerformedServices", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChangedLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("OwnerStaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerStaffProfileId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId", "StartLocal");

                    b.ToTable("TreatmentCourses", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCourseEncounter", b =>
                {
                    b.Property<Guid>("TreatmentCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TreatmentCourseId", "EncounterId");

                    b.HasIndex("EncounterId")
                        .IsUnique();

                    b.ToTable("TreatmentCourseEncounters", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCoursePlannedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChangedLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("LegacyToothCode")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TreatmentCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCatalogItemId");

                    b.HasIndex("TreatmentCourseId");

                    b.ToTable("TreatmentCoursePlannedServices", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Finance.PatientHistoricalReceiptTotal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("CalculationCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PeriodEndLocal")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PeriodStartLocal")
                        .HasColumnType("date");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId", "SourceSystem", "CalculationCode")
                        .IsUnique();

                    b.ToTable("PatientHistoricalReceiptTotals", "finance");
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.ExternalIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InternalEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "InternalEntityId");

                    b.HasIndex("SystemCode", "EntityType", "ExternalId")
                        .IsUnique();

                    b.ToTable("ExternalIdentifiers", "integration");
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.LegacyAppointmentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LegacyComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LegacyDiagnosisText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("LegacyTreatmentId")
                        .HasColumnType("int");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("SystemCode", "ExternalId")
                        .IsUnique();

                    b.ToTable("LegacyAppointmentDetails", "integration");
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.LegacyTreatmentCourseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DoctorDisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("EventLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LegacyTreatmentId")
                        .HasColumnType("int");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientDisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("TreatmentCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TreatmentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "EventLocal");

                    b.HasIndex("StaffProfileId");

                    b.HasIndex("TreatmentCourseId");

                    b.HasIndex("LegacyTreatmentId", "EventLocal");

                    b.HasIndex("SystemCode", "ExternalId")
                        .IsUnique();

                    b.ToTable("LegacyTreatmentCourseEvents", "integration");
                });

            modelBuilder.Entity("Dentalla.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber");

                    b.HasIndex("FullName");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Dentalla.Domain.Scheduling.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LegacyRoomId")
                        .HasColumnType("int");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "StartLocal");

                    b.HasIndex("StaffProfileId", "StartLocal");

                    b.HasIndex("StartLocal");

                    b.ToTable("Appointments", "scheduling");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedFromIp")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ImpersonatedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHashHex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHashHex")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "ExpiresAtUtc");

                    b.ToTable("AuthSessions", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.DelegationGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrantedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrantedToUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GrantedToUserAccountId", "PermissionCode", "ValidFromUtc", "ValidToUtc");

                    b.ToTable("DelegationGrants", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.PermissionDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.ToTable("PermissionDefinitions", "security");

                    b.HasData(
                        new
                        {
                            Code = "appointments.delete",
                            Area = "Appointments",
                            Name = "Delete appointment"
                        },
                        new
                        {
                            Code = "appointments.read",
                            Area = "Appointments",
                            Name = "View appointments"
                        },
                        new
                        {
                            Code = "appointments.write",
                            Area = "Appointments",
                            Name = "Create and edit appointments"
                        },
                        new
                        {
                            Code = "audit.read",
                            Area = "Audit",
                            Name = "View audit log"
                        },
                        new
                        {
                            Code = "clinical.assignDoctor",
                            Area = "Clinical",
                            Name = "Assign or reassign treating doctor"
                        },
                        new
                        {
                            Code = "clinical.read",
                            Area = "Clinical",
                            Name = "View clinical data"
                        },
                        new
                        {
                            Code = "clinical.write",
                            Area = "Clinical",
                            Name = "Create and edit clinical data"
                        },
                        new
                        {
                            Code = "finance.adjust",
                            Area = "Finance",
                            Name = "Perform manual financial adjustments"
                        },
                        new
                        {
                            Code = "finance.discount",
                            Area = "Finance",
                            Name = "Apply discount"
                        },
                        new
                        {
                            Code = "finance.payment",
                            Area = "Finance",
                            Name = "Accept payment"
                        },
                        new
                        {
                            Code = "finance.read",
                            Area = "Finance",
                            Name = "View financial data"
                        },
                        new
                        {
                            Code = "inventory.manage",
                            Area = "Inventory",
                            Name = "Manage equipment and inventory"
                        },
                        new
                        {
                            Code = "marketing.read",
                            Area = "Marketing",
                            Name = "View marketing data"
                        },
                        new
                        {
                            Code = "marketing.write",
                            Area = "Marketing",
                            Name = "Edit marketing data"
                        },
                        new
                        {
                            Code = "patients.delete",
                            Area = "Patients",
                            Name = "Delete or merge patient record"
                        },
                        new
                        {
                            Code = "patients.read",
                            Area = "Patients",
                            Name = "View patient card"
                        },
                        new
                        {
                            Code = "patients.write",
                            Area = "Patients",
                            Name = "Create and edit patient card"
                        },
                        new
                        {
                            Code = "reports.executive",
                            Area = "Reports",
                            Name = "View executive reports"
                        },
                        new
                        {
                            Code = "reports.read",
                            Area = "Reports",
                            Name = "View operational reports"
                        },
                        new
                        {
                            Code = "schedule.manage",
                            Area = "Schedule",
                            Name = "Manage schedule"
                        },
                        new
                        {
                            Code = "schedule.read",
                            Area = "Schedule",
                            Name = "View schedule"
                        },
                        new
                        {
                            Code = "schedule.write",
                            Area = "Schedule",
                            Name = "Create and edit schedule"
                        },
                        new
                        {
                            Code = "security.impersonate",
                            Area = "Security",
                            Name = "Impersonate another account"
                        },
                        new
                        {
                            Code = "security.managePermissions",
                            Area = "Security",
                            Name = "Manage permissions"
                        },
                        new
                        {
                            Code = "security.manageUsers",
                            Area = "Security",
                            Name = "Manage user accounts"
                        },
                        new
                        {
                            Code = "staff.manage",
                            Area = "Staff",
                            Name = "Manage staff"
                        },
                        new
                        {
                            Code = "staff.read",
                            Area = "Staff",
                            Name = "View staff"
                        },
                        new
                        {
                            Code = "templates.manage",
                            Area = "Templates",
                            Name = "Manage clinical templates"
                        });
                });

            modelBuilder.Entity("Dentalla.Domain.Security.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.HasKey("RoleCode", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("RolePermissions", "security");

                    b.HasData(
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "appointments.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "appointments.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "finance.payment",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "patients.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "patients.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "schedule.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "schedule.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "appointments.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "clinical.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "patients.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "reports.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "appointments.delete",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "appointments.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "appointments.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "audit.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "clinical.assignDoctor",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "clinical.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "clinical.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "finance.adjust",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "finance.discount",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "finance.payment",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "finance.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "inventory.manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "marketing.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "marketing.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "patients.delete",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "patients.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "patients.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "reports.executive",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "reports.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "schedule.manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "schedule.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "schedule.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "security.impersonate",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "security.managePermissions",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "security.manageUsers",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "staff.manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "staff.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "templates.manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "appointments.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "clinical.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "clinical.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "patients.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "schedule.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "marketing.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "marketing.write",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "patients.read",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "reports.read",
                            IsAllowed = true
                        });
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("StaffProfileId")
                        .IsUnique();

                    b.ToTable("UserAccounts", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserCredential", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHashBase64")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordSaltBase64")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserAccountId");

                    b.ToTable("UserCredentials", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode");

                    b.HasIndex("UserAccountId", "PermissionCode", "ValidFromUtc");

                    b.ToTable("UserPermissionOverrides", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "RoleCode", "ValidFromUtc");

                    b.ToTable("UserRoleAssignments", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Services.ServiceCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsHistorical")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("IsHistorical", "Name");

                    b.ToTable("ServiceCatalogItems", "services");
                });

            modelBuilder.Entity("Dentalla.Domain.Staff.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("StaffProfiles", "staff");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.Encounter", b =>
                {
                    b.HasOne("Dentalla.Domain.Scheduling.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.PerformedService", b =>
                {
                    b.HasOne("Dentalla.Domain.Clinical.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Services.ServiceCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCourse", b =>
                {
                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerStaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCourseEncounter", b =>
                {
                    b.HasOne("Dentalla.Domain.Clinical.Encounter", null)
                        .WithOne()
                        .HasForeignKey("Dentalla.Domain.Clinical.TreatmentCourseEncounter", "EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Clinical.TreatmentCourse", null)
                        .WithMany()
                        .HasForeignKey("TreatmentCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCoursePlannedService", b =>
                {
                    b.HasOne("Dentalla.Domain.Services.ServiceCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Clinical.TreatmentCourse", null)
                        .WithMany()
                        .HasForeignKey("TreatmentCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Finance.PatientHistoricalReceiptTotal", b =>
                {
                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.LegacyAppointmentDetail", b =>
                {
                    b.HasOne("Dentalla.Domain.Scheduling.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.LegacyTreatmentCourseEvent", b =>
                {
                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dentalla.Domain.Clinical.TreatmentCourse", null)
                        .WithMany()
                        .HasForeignKey("TreatmentCourseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dentalla.Domain.Scheduling.Appointment", b =>
                {
                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dentalla.Domain.Security.AuthSession", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.PermissionDefinition", b =>
                {
                    b.HasMany("Dentalla.Domain.Security.RolePermission", null)
                        .WithOne()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.RolePermission", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserAccount", b =>
                {
                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithOne()
                        .HasForeignKey("Dentalla.Domain.Security.UserAccount", "StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionOverrides");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserCredential", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Dentalla.Domain.Security.UserCredential", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserPermissionOverride", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Security.UserAccount", null)
                        .WithMany("PermissionOverrides")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserRoleAssignment", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.UserAccount", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserAccount", b =>
                {
                    b.Navigation("PermissionOverrides");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
