// <auto-generated />
using System;
using Dentalla.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dentalla.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DentallaDbContext))]
    partial class DentallaDbContextModelSnapshot : ModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dentalla.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RoleContext")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ActorUserAccountId", "OccurredAtUtc");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.ToTable("AuditEvents", "audit");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndedLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("PatientId", "StartedLocal");

                    b.HasIndex("StaffProfileId", "StartedLocal");

                    b.ToTable("Encounters", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.PerformedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short?>("ComplexityId")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("ComplexityValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DiagnosisCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LegacyManipulationOk")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrimeCost")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SourceUnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tooth")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceCatalogItemId");

                    b.HasIndex("StaffProfileId");

                    b.ToTable("PerformedServices", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChangedLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("OwnerStaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerStaffProfileId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId", "StartLocal");

                    b.ToTable("TreatmentCourses", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCourseEncounter", b =>
                {
                    b.Property<Guid>("TreatmentCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TreatmentCourseId", "EncounterId");

                    b.HasIndex("EncounterId")
                        .IsUnique();

                    b.ToTable("TreatmentCourseEncounters", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCoursePlannedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChangedLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("LegacyToothCode")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TreatmentCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCatalogItemId");

                    b.HasIndex("TreatmentCourseId");

                    b.ToTable("TreatmentCoursePlannedServices", "clinical");
                });

            modelBuilder.Entity("Dentalla.Domain.Finance.PatientHistoricalReceiptTotal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("CalculationCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PeriodEndLocal")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PeriodStartLocal")
                        .HasColumnType("date");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId", "SourceSystem", "CalculationCode")
                        .IsUnique();

                    b.ToTable("PatientHistoricalReceiptTotals", "finance");
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.ExternalIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InternalEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "InternalEntityId");

                    b.HasIndex("SystemCode", "EntityType", "ExternalId")
                        .IsUnique();

                    b.ToTable("ExternalIdentifiers", "integration");
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.LegacyAppointmentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LegacyComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LegacyDiagnosisText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("LegacyTreatmentId")
                        .HasColumnType("int");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("SystemCode", "ExternalId")
                        .IsUnique();

                    b.ToTable("LegacyAppointmentDetails", "integration");
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.LegacyTreatmentCourseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DoctorDisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("EventLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LegacyTreatmentId")
                        .HasColumnType("int");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientDisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("TreatmentCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TreatmentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("StaffProfileId");

                    b.HasIndex("TreatmentCourseId");

                    b.HasIndex("LegacyTreatmentId", "EventLocal");

                    b.HasIndex("PatientId", "EventLocal");

                    b.HasIndex("SystemCode", "ExternalId")
                        .IsUnique();

                    b.ToTable("LegacyTreatmentCourseEvents", "integration");
                });

            modelBuilder.Entity("Dentalla.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber");

                    b.HasIndex("FullName");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Dentalla.Domain.Scheduling.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LegacyRoomId")
                        .HasColumnType("int");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("StartLocal");

                    b.HasIndex("PatientId", "StartLocal");

                    b.HasIndex("StaffProfileId", "StartLocal");

                    b.ToTable("Appointments", "scheduling");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedFromIp")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHashHex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHashHex")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "ExpiresAtUtc");

                    b.ToTable("AuthSessions", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.DelegationGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrantedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrantedToUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("LimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RevokedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ValidToUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode");

                    b.HasIndex("GrantedToUserAccountId", "PermissionCode", "ValidFromUtc", "ValidToUtc");

                    b.ToTable("DelegationGrants", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.PermissionDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsClinicalPrivilegeBound")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.ToTable("PermissionDefinitions", "security");

                    b.HasData(
                        new
                        {
                            Code = "Patient.View",
                            Area = "Patient",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Просмотр карточки пациента"
                        },
                        new
                        {
                            Code = "Patient.EditDemographics",
                            Area = "Patient",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Редактирование персональных и контактных данных"
                        },
                        new
                        {
                            Code = "Patient.MergeDuplicates",
                            Area = "Patient",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Объединение дублей пациентов"
                        },
                        new
                        {
                            Code = "Appointment.View",
                            Area = "Schedule",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Просмотр записей"
                        },
                        new
                        {
                            Code = "Appointment.Manage",
                            Area = "Schedule",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Создание, перенос и отмена записей"
                        },
                        new
                        {
                            Code = "ScheduleOperations.BatchBlock",
                            Area = "Schedule",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Массовая блокировка интервалов"
                        },
                        new
                        {
                            Code = "Clinical.Record.View",
                            Area = "Clinical",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Просмотр клинической документации"
                        },
                        new
                        {
                            Code = "Clinical.Note.Edit",
                            Area = "Clinical",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Редактирование текущего дневника"
                        },
                        new
                        {
                            Code = "Clinical.Note.Sign",
                            Area = "Clinical",
                            IsClinicalPrivilegeBound = true,
                            IsSensitive = true,
                            Name = "Подписание медицинской записи"
                        },
                        new
                        {
                            Code = "Clinical.Diagnosis.Manage",
                            Area = "Clinical",
                            IsClinicalPrivilegeBound = true,
                            IsSensitive = false,
                            Name = "Ведение диагнозов"
                        },
                        new
                        {
                            Code = "Clinical.TreatmentPlan.Manage",
                            Area = "Clinical",
                            IsClinicalPrivilegeBound = true,
                            IsSensitive = false,
                            Name = "Ведение плана лечения"
                        },
                        new
                        {
                            Code = "Payment.Accept",
                            Area = "Finance",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Приём оплаты"
                        },
                        new
                        {
                            Code = "Refund.Create",
                            Area = "Finance",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Создание возврата"
                        },
                        new
                        {
                            Code = "Refund.Approve",
                            Area = "Finance",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Утверждение возврата"
                        },
                        new
                        {
                            Code = "CashShift.Close",
                            Area = "Finance",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Закрытие кассовой смены"
                        },
                        new
                        {
                            Code = "Discount.Apply",
                            Area = "Finance",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Применение разрешённой скидки"
                        },
                        new
                        {
                            Code = "Discount.Approve",
                            Area = "Finance",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Утверждение скидки сверх лимита"
                        },
                        new
                        {
                            Code = "Price.Publish",
                            Area = "Finance",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Публикация версии прайс-листа"
                        },
                        new
                        {
                            Code = "Payroll.ViewOwn",
                            Area = "Payroll",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Просмотр собственной выработки"
                        },
                        new
                        {
                            Code = "Payroll.ViewAll",
                            Area = "Payroll",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Просмотр начислений всех сотрудников"
                        },
                        new
                        {
                            Code = "Payroll.Approve",
                            Area = "Payroll",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Утверждение расчёта зарплаты"
                        },
                        new
                        {
                            Code = "Quality.View",
                            Area = "Quality",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Просмотр очереди качества"
                        },
                        new
                        {
                            Code = "Quality.Manage",
                            Area = "Quality",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Управление внутренним контролем качества"
                        },
                        new
                        {
                            Code = "Sms.SendTemplate",
                            Area = "Communication",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Отправка SMS по утверждённому шаблону"
                        },
                        new
                        {
                            Code = "Sms.SendFreeText",
                            Area = "Communication",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Отправка свободного SMS"
                        },
                        new
                        {
                            Code = "Marketing.View",
                            Area = "Marketing",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Просмотр маркетинговых данных"
                        },
                        new
                        {
                            Code = "Marketing.Manage",
                            Area = "Marketing",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = false,
                            Name = "Управление лидами, источниками и кампаниями"
                        },
                        new
                        {
                            Code = "Marketing.Campaign.Execute",
                            Area = "Marketing",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Запуск массовой коммуникации"
                        },
                        new
                        {
                            Code = "ExternalIntegration.Manage",
                            Area = "System",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Подключение и управление внешними сервисами"
                        },
                        new
                        {
                            Code = "Staff.Manage",
                            Area = "System",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Управление сотрудниками"
                        },
                        new
                        {
                            Code = "RBAC.ManageRoleProfile",
                            Area = "System",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Изменение базовых прав ролей"
                        },
                        new
                        {
                            Code = "RBAC.ManageUserOverride",
                            Area = "System",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Индивидуальные Allow/Deny сотрудника"
                        },
                        new
                        {
                            Code = "RBAC.Delegate",
                            Area = "System",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Временное делегирование полномочий"
                        },
                        new
                        {
                            Code = "RBAC.SwitchRoleContext",
                            Area = "System",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Переключение Director между рабочими контекстами ролей"
                        },
                        new
                        {
                            Code = "Audit.View",
                            Area = "System",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Просмотр аудита"
                        },
                        new
                        {
                            Code = "SystemSettings.Manage",
                            Area = "System",
                            IsClinicalPrivilegeBound = false,
                            IsSensitive = true,
                            Name = "Системные настройки"
                        });
                });

            modelBuilder.Entity("Dentalla.Domain.Security.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.HasKey("RoleCode", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("RolePermissions", "security");

                    b.HasData(
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "Patient.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "Appointment.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "Clinical.Record.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "Clinical.Note.Edit",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "Clinical.Note.Sign",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "Clinical.Diagnosis.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "Clinical.TreatmentPlan.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Doctor",
                            PermissionCode = "Payroll.ViewOwn",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Patient.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Patient.EditDemographics",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Appointment.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Appointment.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "ScheduleOperations.BatchBlock",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Payment.Accept",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Refund.Create",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "CashShift.Close",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Discount.Apply",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Sms.SendTemplate",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Administrator",
                            PermissionCode = "Sms.SendFreeText",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "Patient.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "Clinical.Record.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "Appointment.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "Marketing.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Marketer",
                            PermissionCode = "Marketing.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Patient.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Appointment.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Clinical.Record.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Clinical.Note.Edit",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Clinical.Note.Sign",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Clinical.Diagnosis.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Clinical.TreatmentPlan.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Quality.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Quality.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "ChiefMedicalOfficer",
                            PermissionCode = "Payroll.ViewOwn",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Patient.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Patient.EditDemographics",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Patient.MergeDuplicates",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Appointment.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Appointment.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "ScheduleOperations.BatchBlock",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Clinical.Record.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Clinical.Note.Edit",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Clinical.Note.Sign",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Clinical.Diagnosis.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Clinical.TreatmentPlan.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Payment.Accept",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Refund.Create",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Refund.Approve",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "CashShift.Close",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Discount.Apply",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Discount.Approve",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Price.Publish",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Payroll.ViewOwn",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Payroll.ViewAll",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Payroll.Approve",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Quality.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Quality.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Sms.SendTemplate",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Sms.SendFreeText",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Marketing.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Marketing.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Marketing.Campaign.Execute",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "ExternalIntegration.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Staff.Manage",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "RBAC.ManageRoleProfile",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "RBAC.ManageUserOverride",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "RBAC.Delegate",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "RBAC.SwitchRoleContext",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "Audit.View",
                            IsAllowed = true
                        },
                        new
                        {
                            RoleCode = "Director",
                            PermissionCode = "SystemSettings.Manage",
                            IsAllowed = true
                        });
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("StaffProfileId")
                        .IsUnique();

                    b.ToTable("UserAccounts", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserCredential", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHashBase64")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("int");

                    b.Property<string>("PasswordSaltBase64")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserAccountId");

                    b.ToTable("UserCredentials", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrantedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode");

                    b.HasIndex("UserAccountId", "PermissionCode", "ValidFromUtc");

                    b.ToTable("UserPermissionOverrides", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrantedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "RoleCode", "ValidFromUtc");

                    b.ToTable("UserRoleAssignments", "security");
                });

            modelBuilder.Entity("Dentalla.Domain.Services.ServiceCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsHistorical")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("IsHistorical", "Name");

                    b.ToTable("ServiceCatalogItems", "services");
                });

            modelBuilder.Entity("Dentalla.Domain.Staff.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("StaffProfiles", "staff");
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.Encounter", b =>
                {
                    b.HasOne("Dentalla.Domain.Scheduling.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.PerformedService", b =>
                {
                    b.HasOne("Dentalla.Domain.Clinical.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Services.ServiceCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCourse", b =>
                {
                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerStaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCourseEncounter", b =>
                {
                    b.HasOne("Dentalla.Domain.Clinical.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Clinical.TreatmentCourse", null)
                        .WithMany()
                        .HasForeignKey("TreatmentCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Clinical.TreatmentCoursePlannedService", b =>
                {
                    b.HasOne("Dentalla.Domain.Services.ServiceCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Clinical.TreatmentCourse", null)
                        .WithMany()
                        .HasForeignKey("TreatmentCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Finance.PatientHistoricalReceiptTotal", b =>
                {
                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.LegacyAppointmentDetail", b =>
                {
                    b.HasOne("Dentalla.Domain.Scheduling.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Integration.LegacyTreatmentCourseEvent", b =>
                {
                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dentalla.Domain.Clinical.TreatmentCourse", null)
                        .WithMany()
                        .HasForeignKey("TreatmentCourseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dentalla.Domain.Scheduling.Appointment", b =>
                {
                    b.HasOne("Dentalla.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dentalla.Domain.Security.AuthSession", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.DelegationGrant", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.RolePermission", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserAccount", b =>
                {
                    b.HasOne("Dentalla.Domain.Staff.StaffProfile", null)
                        .WithOne()
                        .HasForeignKey("Dentalla.Domain.Security.UserAccount", "StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserCredential", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Dentalla.Domain.Security.UserCredential", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserPermissionOverride", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentalla.Domain.Security.UserAccount", null)
                        .WithMany("PermissionOverrides")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserRoleAssignment", b =>
                {
                    b.HasOne("Dentalla.Domain.Security.UserAccount", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dentalla.Domain.Security.UserAccount", b =>
                {
                    b.Navigation("PermissionOverrides");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
